### ISSUE TITLE
Unhandled Exception creating Admin Account

### ISSUE THREAD

**Issue by RiajuuBakahatsu** [dequis/wakarimasen#56]
Title says all, basically. I've set the software up, yet when I go to enter a username and password and hit the Go button, I get an Unhandled exception.

**Comment by dequis** [comment]
Well, first,

>Wakarimasen is still experimental software - use it at your own risk and if you know how to fix stuff when it breaks.

Having said that, you might want to look into getting a traceback for that error.

**Comment by RiajuuBakahatsu** [comment]
Sorry, it was my fault for not being more specific. When I look in the error logs, this is what I get 

>Traceback (most recent call last):
  File "/var/www/html/wakarimasen/wakarimasen.py", line 63, in application
    return list(function(environ, start_response))
  File "/var/www/html/wakarimasen/app.py", line 286, in task_setup
    return staff_interface.do_first_time_setup(**kwargs)
TypeError: do_first_time_setup() got an unexpected keyword argument 'admin'
